### ISSUE TITLE
What service is this?

### ISSUE THREAD

**Issue by joq3** [leram84/layer.Cake#10]
Hi,

Just found your theme, and what service is running on this screenshot?
https://raw.githubusercontent.com/leram84/layer.Cake/Screenshots/theBlur1.jpg
It looks fantastic, I really want to have that, does it integrate with Sonarr in the calendar? And download services like Transmission and sabnzbd?

One other thing, when installing this directly from Organizr there are these instructions:
`Step 1: Choose your button html from one of the option below and edit if needed (Make sure to update as there are changes from the beta)
Default For Plex Users
For Plex Users who want the chat button to go to the chat tab instead of the chat sidebar
Default For Emby Users
For Emby Users who want the chat button to go to the chat tab instead of the chat sidebar
Step 2: Upload your top bar logo to Organizr from the "Edit Tabs" screen under the name "blurlogo.png".
Step 3: Select theBlur as your theme, save, refresh and enjoy!`

Where do I put the html?

Also, why does your settings-page here look different?
https://raw.githubusercontent.com/leram84/layer.Cake/Screenshots/settings.PNG
Mine is small icons on the left hand side, which pull out one by one?

**Comment by GilbN** [comment]
If you are talking about the homepage. Just add a tab with homepage.php in Organizr
https://github.com/causefx/Organizr/wiki/Optional-Homepage

Custom HTML: Settings -> Homepage settings -> HTML

And the settings-page screenshot is from an older Organizr build

**Comment by gilbN** [comment]
https://github.com/causefx/Organizr/wiki/Optional-Homepage

**Comment by leram84** [comment]
^ that, and yeah, sorry about the lack of clarity about the html buttons. I totally forgot i removed the part about where to put them when i updated the instructions! Ill fix that now :)
