### ISSUE TITLE
Image Upload Success

### ISSUE THREAD

**Issue by jonathanfinley** [leram84/layer.Cake#2]
So I uploaded some images into Org and noticed that the theme did not fall into these blocks.

Thanks!

![screen shot 2017-07-30 at 7 20 26 pm](https://user-images.githubusercontent.com/23283167/28757974-86852f50-755c-11e7-9cc5-fceb069cdfb0.png)

**Comment by jonathanfinley** [comment]
![screen shot 2017-07-30 at 7 25 51 pm](https://user-images.githubusercontent.com/23283167/28757986-f4067cd2-755c-11e7-977b-57e83a891bbc.png)

**Comment by leram84** [comment]
All straight :)

**Comment by leram84** [comment]
All straight :)
