### ISSUE TITLE
Test iFrame box need wrapping

### ISSUE THREAD

**Issue by jonathanfinley** [leram84/layer.Cake#3]
<img width="962" alt="screen shot 2017-08-02 at 6 17 13 pm" src="https://user-images.githubusercontent.com/23283167/28897902-fb93ffb4-77b0-11e7-9ec2-608b8ab44ad8.png">
found the following: feel free to change 😋 

```
.modal-content { background-color: #fff } <<< entire box
.in .modal-body .material { background: #fff } <<< text entry background
```

**Comment by leram84** [comment]
yeah... i was being lazy. I had actually already made the background white, which is why you can't see anything if your tLayerTwo is also white. My bady... skinned the whole tile now :)
