### ISSUE TITLE
Wrong password error

### ISSUE THREAD

**Issue by jonathanfinley** [leram84/layer.Cake#4]
![screen shot 2017-08-04 at 9 42 37 am](https://user-images.githubusercontent.com/23283167/28972767-e24f2f98-78fe-11e7-87b1-20ff74137f15.png)

**Comment by leram84** [comment]
Since dev isn't actually supported yet anyway, im just gonna close this. I'm sure cause will fix the bug before the next org update.

**Comment by jonathanfinley** [comment]
Sounds good. Thanks!
