### ISSUE TITLE
Plug in idea:  Live display of services

### ISSUE THREAD

**Issue by seanvree** [leram84/layer.Cake#6]
Plugin:  https://github.com/seanvree/Monitorr

This is a screenshot of my working live Demo:

![image](https://user-images.githubusercontent.com/8906637/30247520-856205a0-95cb-11e7-8c52-bbccb9b8b51a.png)

![image](https://user-images.githubusercontent.com/8906637/30247524-8f26b068-95cb-11e7-8d49-6a75dd952e94.png)

let's get to work.

**Comment by leram84** [comment]
Awesome! but i dont get it, what does lc have to do w this?

**Comment by seanvree** [comment]
integrated into org. closed.

**Comment by leram84** [comment]
lol
