### ISSUE TITLE
Calendar legend wrong

### ISSUE THREAD

**Issue by dejected1** [leram84/layer.Cake#8]
So i had this setup in orgainzr 1.44 and was working great. i then updated to organizr 1.50, and applied the advanced template from within organizr for layer cake. The legend for the calendar page is incorrect. The word "Legend" that you click on now to view the legend is the color for calAvailable but after the new pop up window pops up it shows the default green for available.  Not sure if this a change needed for layer cake or orgainzr.  This is my css:

/* This block is for the Calendar Color Codes */
    --color-calAvailable:       #ffad34;
    --color-calUnavailable:     #700012;
    --color-calUnreleased:      #444444;
    --color-calPremier:         #228b22;

Here are some pics for help:
![image](https://user-images.githubusercontent.com/26720061/31454535-96f72590-ae6a-11e7-9eff-7a807ad3bcb7.JPG)
![image2](https://user-images.githubusercontent.com/26720061/31454540-99c156d8-ae6a-11e7-8d8c-d0834a6ef69d.JPG)

**Comment by leram84** [comment]
Thanks for the detailed writeup! I have been very busy getting the new blur theme up and have yet to update cake proper with all the 1.5 upgrades. This is one of MANY things i need to update for that. As soon as i push blur out of beta i will go back and straighten all the basic/advanced issues. Shouldn't be more than a few days. Ill let you know when its all done :)

**Comment by leram84** [comment]
ok, so now that its all done, are you still wanting to use this theme? or have you moved on to blur/unblur?

**Comment by dejected1** [comment]
i am using unblur currently and generally like it. Although the same calendar legend bug exists for unblur  (and i assume blur) as well. If you edit the calendar colors it doesn't update the legend. I was able to find the css code to update the legend thou. I add this the homepage html settings. 

<style>.label.label-primary.well-sm {
            background: #E16819;
        }
        .label.label-danger.well-sm {
            background: #ffad34;
        }
        .label.indigo-bg.well-sm {
            background: #444444 !important;
        }
        .label.light-blue-bg.well-sm {
            background: #228b22 !important;
        }
</style>

As a secondary issue, is there an easy way to change the font colors for unblur or blur. You let us change the calendar colors real easy but not the font colors for the calendar items. Subsequently some colors just don't work well. I know i can probably dig through the css and find it but i like the ease of use from within gui. Thanks!

**Comment by leram84** [comment]
ahhh, good catch. Yeah, sorry, there was a bug w the legend available color... all good now. As for the other issue. I could make options, but i was initially trying to make the user input part as simple as possible. If i add options to start changing text colors, there are a bunch of request for other text and fonts, etc... Ill have to think about this. But i might end up making an "advanced" version with options to change a bunch of stuff... not sure yet.

**Comment by dejected1** [comment]
Well that's an interesting thing. It loads with the wrong color still but then after a second it click into the right colors. Then when hitting ok again it  defaults to the wrong colors before closing. When i had the labels manually defined in the homepage css it didn't do that.  Here is a gif because words are hard:

![image](https://user-images.githubusercontent.com/26720061/33244076-ff65b206-d2ad-11e7-9ec2-fa51caf40c76.gif)


so i guess it works.

**Comment by leram84** [comment]
sorry for the delay... had to rework a few things and didn't want to push till i was sure it wasn't gonna cause any more issues. But all good now. should work fully as intended... lmk if not
